[package]
name = "strategic-communication"
version = "1.0.0"
authors = ["Steven Goldberg"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
regex = "1.3.9"
lazy_static = "1.4.0"
log = "0.4.0"
env_logger = "0.7.1"
rand = "0.7.3"